// GENERATED FILE -- DO NOT EDIT
// Generated by libpan
// Contains:
//  - server person:wall(...)
//  - server person:sees(...)
//  - server person:at(...)
//  - server person:hp(...)
//  - server person:tick(...)
//  - client person:attack(...)
//  - client person:move(...)

#pragma once
#include "libpan_cxx_macros.hpp"

PAN_GH_DEFS_BEGIN

PAN_GH_MSG(PAN_GH_SERVER, person, wall, "person", "wall",
    int32_t          x;
    int32_t          y;
)
PAN_GH_DECODE(PAN_GH_SERVER, person, wall, "person", "wall",
    PAN_GH_READ(&self->x, sizeof(self->x));
    PAN_GH_READ(&self->y, sizeof(self->y));
)
PAN_GH_ENCODE(PAN_GH_SERVER, person, wall, "person", "wall",
    uint16_t len = 0;
    len += sizeof(self->x);
    len += sizeof(self->y);
    PAN_GH_HEADER("person", "wall", len);
    PAN_GH_WRITE(&self->x, sizeof(self->x));
    PAN_GH_WRITE(&self->y, sizeof(self->y));
)

PAN_GH_MSG(PAN_GH_SERVER, person, sees, "person", "sees",
    int32_t          x;
    int32_t          y;
    PAN_GH_ID        who;
)
PAN_GH_DECODE(PAN_GH_SERVER, person, sees, "person", "sees",
    PAN_GH_READ(&self->x, sizeof(self->x));
    PAN_GH_READ(&self->y, sizeof(self->y));
    PAN_GH_READ(&self->who, sizeof(self->who));
)
PAN_GH_ENCODE(PAN_GH_SERVER, person, sees, "person", "sees",
    uint16_t len = 0;
    len += sizeof(self->x);
    len += sizeof(self->y);
    len += sizeof(self->who);
    PAN_GH_HEADER("person", "sees", len);
    PAN_GH_WRITE(&self->x, sizeof(self->x));
    PAN_GH_WRITE(&self->y, sizeof(self->y));
    PAN_GH_WRITE(&self->who, sizeof(self->who));
)

PAN_GH_MSG(PAN_GH_SERVER, person, at, "person", "at",
    int32_t          x;
    int32_t          y;
)
PAN_GH_DECODE(PAN_GH_SERVER, person, at, "person", "at",
    PAN_GH_READ(&self->x, sizeof(self->x));
    PAN_GH_READ(&self->y, sizeof(self->y));
)
PAN_GH_ENCODE(PAN_GH_SERVER, person, at, "person", "at",
    uint16_t len = 0;
    len += sizeof(self->x);
    len += sizeof(self->y);
    PAN_GH_HEADER("person", "at", len);
    PAN_GH_WRITE(&self->x, sizeof(self->x));
    PAN_GH_WRITE(&self->y, sizeof(self->y));
)

PAN_GH_MSG(PAN_GH_SERVER, person, hp, "person", "hp",
    int32_t          hp;
)
PAN_GH_DECODE(PAN_GH_SERVER, person, hp, "person", "hp",
    PAN_GH_READ(&self->hp, sizeof(self->hp));
)
PAN_GH_ENCODE(PAN_GH_SERVER, person, hp, "person", "hp",
    uint16_t len = 0;
    len += sizeof(self->hp);
    PAN_GH_HEADER("person", "hp", len);
    PAN_GH_WRITE(&self->hp, sizeof(self->hp));
)

PAN_GH_MSG(PAN_GH_SERVER, person, tick, "person", "tick",
)
PAN_GH_DECODE(PAN_GH_SERVER, person, tick, "person", "tick",
)
PAN_GH_ENCODE(PAN_GH_SERVER, person, tick, "person", "tick",
    uint16_t len = 0;
    PAN_GH_HEADER("person", "tick", len);
)

PAN_GH_MSG(PAN_GH_CLIENT, person, attack, "person", "attack",
    PAN_GH_ID        whom;
)
PAN_GH_DECODE(PAN_GH_CLIENT, person, attack, "person", "attack",
    PAN_GH_READ(&self->whom, sizeof(self->whom));
)
PAN_GH_ENCODE(PAN_GH_CLIENT, person, attack, "person", "attack",
    uint16_t len = 0;
    len += sizeof(self->whom);
    PAN_GH_HEADER("person", "attack", len);
    PAN_GH_WRITE(&self->whom, sizeof(self->whom));
)

PAN_GH_MSG(PAN_GH_CLIENT, person, move, "person", "move",
    int8_t           dx;
    int8_t           dy;
)
PAN_GH_DECODE(PAN_GH_CLIENT, person, move, "person", "move",
    PAN_GH_READ(&self->dx, sizeof(self->dx));
    PAN_GH_READ(&self->dy, sizeof(self->dy));
)
PAN_GH_ENCODE(PAN_GH_CLIENT, person, move, "person", "move",
    uint16_t len = 0;
    len += sizeof(self->dx);
    len += sizeof(self->dy);
    PAN_GH_HEADER("person", "move", len);
    PAN_GH_WRITE(&self->dx, sizeof(self->dx));
    PAN_GH_WRITE(&self->dy, sizeof(self->dy));
)

PAN_GH_DEFS_END
