// GENERATED FILE -- DO NOT EDIT
// Generated by libpan
// Contains:
//  - client srv:username(...)
//  - server srv:r.setLvl(...)
//  - client srv:setLvl(...)
//  - server srv:level(...)
//  - server srv:id(...)
//  - server srv:name(...)
//  - server srv:hasPref(...)

#pragma once
#include "libpan_cxx_macros.hpp"

PAN_GH_DEFS_BEGIN

PAN_GH_MSG(PAN_GH_CLIENT, srv, username, "srv", "username",
    PAN_GH_SLICE     name;
)
PAN_GH_DECODE(PAN_GH_CLIENT, srv, username, "srv", "username",
    uint16_t name_len = 0;
    PAN_GH_READ(&name_len, 2);
    PAN_GH_READ_SLICE(&self->name, name_len);
)
PAN_GH_ENCODE(PAN_GH_CLIENT, srv, username, "srv", "username",
    uint16_t len = 0;
    len += 2 + PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_HEADER("srv", "username", len);
    uint16_t name_len = PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_WRITE(&name_len, 2);
    PAN_GH_WRITE_SLICE(&self->name, name_len);
)

PAN_GH_MSG(PAN_GH_SERVER, srv, r_setLvl, "srv", "r.setLvl",
    PAN_GH_ID        msg;
    bool             ok;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, r_setLvl, "srv", "r.setLvl",
    PAN_GH_READ(&self->msg, sizeof(self->msg));
    PAN_GH_READ(&self->ok, sizeof(self->ok));
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, r_setLvl, "srv", "r.setLvl",
    uint16_t len = 0;
    len += sizeof(self->msg);
    len += sizeof(self->ok);
    PAN_GH_HEADER("srv", "r.setLvl", len);
    PAN_GH_WRITE(&self->msg, sizeof(self->msg));
    PAN_GH_WRITE(&self->ok, sizeof(self->ok));
)

PAN_GH_MSG(PAN_GH_CLIENT, srv, setLvl, "srv", "setLvl",
    PAN_GH_CHAR64    level;
)
PAN_GH_DECODE(PAN_GH_CLIENT, srv, setLvl, "srv", "setLvl",
    PAN_GH_READ(&self->level, sizeof(self->level));
)
PAN_GH_ENCODE(PAN_GH_CLIENT, srv, setLvl, "srv", "setLvl",
    uint16_t len = 0;
    len += sizeof(self->level);
    PAN_GH_HEADER("srv", "setLvl", len);
    PAN_GH_WRITE(&self->level, sizeof(self->level));
)

PAN_GH_MSG(PAN_GH_SERVER, srv, level, "srv", "level",
    PAN_GH_CHAR64    level;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, level, "srv", "level",
    PAN_GH_READ(&self->level, sizeof(self->level));
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, level, "srv", "level",
    uint16_t len = 0;
    len += sizeof(self->level);
    PAN_GH_HEADER("srv", "level", len);
    PAN_GH_WRITE(&self->level, sizeof(self->level));
)

PAN_GH_MSG(PAN_GH_SERVER, srv, id, "srv", "id",
    PAN_GH_ID        clientId;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, id, "srv", "id",
    PAN_GH_READ(&self->clientId, sizeof(self->clientId));
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, id, "srv", "id",
    uint16_t len = 0;
    len += sizeof(self->clientId);
    PAN_GH_HEADER("srv", "id", len);
    PAN_GH_WRITE(&self->clientId, sizeof(self->clientId));
)

PAN_GH_MSG(PAN_GH_SERVER, srv, name, "srv", "name",
    PAN_GH_SLICE     name;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, name, "srv", "name",
    uint16_t name_len = 0;
    PAN_GH_READ(&name_len, 2);
    PAN_GH_READ_SLICE(&self->name, name_len);
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, name, "srv", "name",
    uint16_t len = 0;
    len += 2 + PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_HEADER("srv", "name", len);
    uint16_t name_len = PAN_GH_SLICE_LEN(&self->name);
    PAN_GH_WRITE(&name_len, 2);
    PAN_GH_WRITE_SLICE(&self->name, name_len);
)

PAN_GH_MSG(PAN_GH_SERVER, srv, hasPref, "srv", "hasPref",
    PAN_GH_CHAR64    pref;
)
PAN_GH_DECODE(PAN_GH_SERVER, srv, hasPref, "srv", "hasPref",
    PAN_GH_READ(&self->pref, sizeof(self->pref));
)
PAN_GH_ENCODE(PAN_GH_SERVER, srv, hasPref, "srv", "hasPref",
    uint16_t len = 0;
    len += sizeof(self->pref);
    PAN_GH_HEADER("srv", "hasPref", len);
    PAN_GH_WRITE(&self->pref, sizeof(self->pref));
)

PAN_GH_DEFS_END
